# -*- coding: utf-8 -*-
"""biomec1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hrDUJlEO4oohofnB5GW2WajOX_wGLfjz
"""

def pega_pontos():
  xc1 = float(input("Defina a coordenada no eixo X da camera 1:"))
  yc1 = float(input("Defina a coordenada no eixo Y da camera 1:"))
  xc2 = float(input("Defina a coordenada no eixo X da camera 2:"))
  yc2 = float(input("Defina a coordenada no eixo Y da camera 2:"))
  #zc1 = float(input("Defina a coordenada no eixo Z da camera 1:"))

  xp1 = float(input("Defina a coordenada no eixo X da Projecao 1:"))
  yp1 = float(input("Defina a coordenada no eixo Y da Projecao 1:"))
  xp2 = float(input("Defina a coordenada no eixo X da Projecao 2:"))
  yp2 = float(input("Defina a coordenada no eixo Y da Projecao 2:"))
  #zp1 = float(input("Defina a coordenada no eixo Z da Projecao:"))


  mr1 = (yp1 - yc1) / (xp1 - xc1) # coeficiente angular de r1
  mr2 = (yp2 - yc2) / (xp2 - xc2) # coeficiente angular de r2

  br1 = -1 * (mr1 * xc1 - yc1) # coeficiente linear de r1
  br2 = -1 * (mr2 * xc2 - yc2) # coeficiente linear de r2

  x = (-(mr2*xc2) + yc2 + (mr1*xc1) - yc1) / (mr1 - mr2) # x do cruzamento

  y = (mr1*x)  - (mr1*xc1) + yc1 # y do cruzamento

  return x, y

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt

def plotagrafico(x,y):
  plt.plot(x, y, 'o', color='red')

#pontos de teste
a = (211.000,	0,	133.900,	131.400,	384.800,	179.400,	0)

X, Y = pega_pontos()
plotagrafico(X, Y)